// Frontend/src/app/Components/dashboard/dashboard.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-dashboard",
  templateUrl: "./dashboard.component.html",
  styleUrls: ["./dashboard.component.scss"],
})
export class DashboardComponent {
  createForm: boolean = false;

  toggleForm(): void {
    this.createForm = !this.createForm;
  }
}

<!-- SET REMINDERS/NOTIFICATIONS SO USER CAN COME BACK ON RIGHT DAY -->
<main class="dashboard-container">
  <div class="d-sidebar">
    <div class="sidebar-profile">
      <div class="temp-circ"></div>
      <p>Jason</p>
    </div>

    <div class="sidebar-tab">
      <mat-icon fontIcon="dashboard" class="sidebar-icon"></mat-icon>
      <h1>Dashboard</h1>
    </div>

    <div class="sidebar-tab">
      <mat-icon fontIcon="bookmarks" class="sidebar-icon"></mat-icon>
      <h1>Bookmark</h1>
    </div>

    <div class="sidebar-tab">
      <mat-icon fontIcon="folder" class="sidebar-icon"></mat-icon>
      <h1>Folders</h1>
    </div>

    <div class="sidebar-tab">
      <mat-icon fontIcon="upcoming" class="sidebar-icon"></mat-icon>
      <h1>Upcoming</h1>
    </div>

    <div class="sidebar-tab">
      <mat-icon fontIcon="delete" class="sidebar-icon"></mat-icon>
      <h1>Trash</h1>
    </div>

    <div class="sidebar-tab sidebar-bottom">
      <mat-icon fontIcon="logout" class="sidebar-icon"></mat-icon>
      <h1>Logout</h1>
    </div>

    <div class="sidebar-tab" style="margin-bottom: 5vh">
      <mat-icon fontIcon="settings" class="sidebar-icon"></mat-icon>
      <h1>Settings</h1>
    </div>
  </div>

  <div class="d-main">
    <nav class="main-nav">
      <p>Dashboard</p>

      <div class="nav-right">
        <div class="nav-search">
          <mat-icon fontIcon="search" class="search-icon"></mat-icon>
          <input id="search" placeholder="Search" />
        </div>

        <div class="nav-function">
          <button (click)="toggleForm()">
            <mat-icon fontIcon="add"></mat-icon>
            Add a new link
          </button>

          <div *ngIf="createForm === true" class="create-form-overlay">
            <div class="create-form">
              <p (click)="toggleForm()">CLOSE</p>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="main-content">
      <div class="content-nav">
        <p>Recently Viewed</p>
        <p>Filter</p>
        <mat-icon fontIcon="apps"></mat-icon>
        <mat-icon fontIcon="view_list"></mat-icon>
        <mat-icon fontIcon="view_headline"></mat-icon>
      </div>
      <div class="content-grid">
        <app-link></app-link>
      </div>
    </div>
  </div>
</main>

// Frontend/src/Components/Dashboard.tsx
import React from "react";
import "../Styles/Dashboard.scss";

import { RiArrowDropDownLine } from "react-icons/ri";
import {
  AiOutlineSearch,
  AiOutlinePushpin,
  AiOutlineFolder,
  AiOutlinePlus,
  AiOutlineLink,
} from "react-icons/ai";
import { TfiLink } from "react-icons/tfi";
import { BsGrid } from "react-icons/bs";
import { CiGrid2H } from "react-icons/ci";
import { FiMenu } from "react-icons/fi";

function Dashboard() {
  // SET REMINDERS/NOTIFICATIONS SO USER CAN COME BACK ON RIGHT DAY

  return (
    <main className="dashboard-container">
      <div className="d-sidebar">
        <div className="sidebar-profile">
          <p>Jason</p>
          <RiArrowDropDownLine size={25} />
        </div>

        <div className="sidebar-search">
          <AiOutlineSearch color="#5b4dbe" />
          <input id="search" placeholder="Search links or folders..."></input>
        </div>

        <div className="sidebar-pins">
          <AiOutlinePushpin color="#5b4dbe" />
          <h1>Pinned</h1>
        </div>

        <div className="sidebar-folders">
          <div className="folders-flex">
            <AiOutlineFolder color="#5b4dbe" />
            <h1>Folders</h1>
          </div>

          <button>
            <AiOutlinePlus color="#5b4dbe" size={20} />
            Create new folder
          </button>
        </div>
      </div>

      <div className="d-main">
        <div className="main-title">Recent</div>

        <div className="main-functions">
          <button>
            <AiOutlineLink /> Add Link{" "}
          </button>
          <button>
            <TfiLink />
            Add Multiple
          </button>
        </div>

        <div className="main-content">
          <div className="content-nav">
            <p>Recently Viewed</p>
            <p>Filter</p>
            <BsGrid />
            <CiGrid2H />
            <FiMenu />
          </div>
          <div className="content-grid"></div>
        </div>
      </div>
    </main>
  );
}

export default Dashboard;
