// Frontend/src/app/Components/home/home.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.scss"],
})
export class HomeComponent {
  // Toggle FAQ
  activeID: number = 0;

  toggleFAQ(id: number): void {
    this.activeID = this.activeID === id ? 0 : id;
  }

  faqs = [
    {
      id: 1,
      question: "What is LinkStorage and how does it work?",
      answer:
        "Our website is a link saver tool that allows you to store and organize your favorite links all in one place. You can save URLs, filter and search through your collection, and even preview the content of the links directly on our platform.",
    },

    {
      id: 2,
      question: "Is my personal information or data shared with third parties?",
      answer:
        "No, your personal information or data will never be shared with third parties. We prioritize the security and privacy of your information.",
    },

    {
      id: 3,
      question: "Is there a browser extension for LinkStorage?",
      answer:
        "Not yet, but we're actively working on developing a browser extension to enhance your LinkStorage experience. Stay tuned for updates on this feature!",
    },

    {
      id: 4,
      question:
        "Do you offer a premium or paid version of LinkStorage with additional features?",
      answer:
        "No, every feature of LinkStorage is available for free. We believe in providing a comprehensive and valuable link-saving experience to all our users.",
    },

    {
      id: 5,
      question: "What features are available on LinkStorage?",
      answer:
        "LinkStorage offers a range of features to streamline your link-saving process, including filtering options like sorting and searching, thumbnail previews for easy identification, reminders to keep you organized, and the ability to create folders for efficient categorization.",
    },

    {
      id: 6,
      question: "What types of links can I save? Are there any restrictions?",
      answer:
        "There are no restrictions on the types of links you can save in LinkStorage. You can save links to websites, articles, videos, and more, making it a versatile tool for all your link-saving needs.",
    },

    {
      id: 7,
      question: "Can I share my folders/links to others?",
      answer:
        "Absolutely! You have the ability to generate shareable links for your folders, allowing you to easily share collections of links with others.",
    },

    {
      id: 8,
      question:
        "How can I suggest new features or improvements for LinkStorage?",
      answer:
        "We value your input! To suggest new features or improvements for LinkStorage, please visit our Contact Section below. We're always eager to hear your ideas and make our platform even better based on user feedback.",
    },
  ];

  // Anchor Link Scroll
  scroll(el: HTMLElement) {
    el.scrollIntoView();
  }
}

<main class="home-page">
  <header class="landing-page" #home>
    <nav class="landing-nav">
      <span class="landing-nav-left">
        <h1>linkstorag<span>e</span></h1>

        <a routerLink="/versions">Changelogs</a>

        <span
          class="material-symbols-outlined theme-toggle"
          (click)="toggleTheme('light')"
          *ngIf="this.theme === 'dark'"
        >
          light_mode
        </span>

        <span
          class="material-symbols-outlined theme-toggle"
          (click)="toggleTheme('dark')"
          *ngIf="this.theme === 'light'"
        >
          dark_mode
        </span>
      </span>

      <span class="landing-nav-right">
        <a routerLink="/user/login" *ngIf="!user" class="home-login">Log In</a>

        <a routerLink="/user/register" *ngIf="!user" class="register-button">
          Get Started
        </a>

        <a
          routerLink="/dashboard"
          *ngIf="user"
          class="register-button dashboard-button"
          >Dashboard</a
        >
      </span>
    </nav>

    <h1 class="landing-title">Save + Preview & Track Your Links</h1>

    <div class="landing-body">
      <a routerLink="/user/register" *ngIf="!user" class="register-button">
        Try for Free
      </a>

      <a routerLink="/dashboard" *ngIf="user" class="dashboard-button"
        >Dashboard</a
      >

      <section class="home_showcase">
        <div class="showcase_header" (click)="toggleShowcase()">
          <span class="material-icons-round"> play_circle </span>
          <h1>Play Demo</h1>
        </div>
      </section>
    </div>
  </header>

  <div class="showcase_border" *ngIf="videoShowcase">
    <iframe
      width="800"
      height="500"
      src="https://www.youtube.com/embed/OrvRE0zM_QY?si=LnaUI-mnPKAjiRoW?autoplay=1&mute=1"
      title="YouTube video player"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      referrerpolicy="strict-origin-when-cross-origin"
      allowfullscreen
      class="showcase_video"
    ></iframe>
  </div>

  <section class="home_gallery">
    <div class="gallery-flex">
      <p
        (click)="changePic(0)"
        [ngClass]="activePic === 0 ? 'active-img' : 'inactive-img'"
      >
        <mat-icon fontIcon="dashboard"></mat-icon>
        Dashboard
      </p>
      <p
        (click)="changePic(1)"
        [ngClass]="activePic === 1 ? 'active-img' : 'inactive-img'"
      >
        <mat-icon fontIcon="description"></mat-icon>
        URL Bank
      </p>
      <p
        (click)="changePic(2)"
        [ngClass]="activePic === 2 ? 'active-img' : 'inactive-img'"
      >
        <mat-icon fontIcon="share"></mat-icon>
        Folder Sharing
      </p>
      <p
        (click)="changePic(3)"
        [ngClass]="activePic === 3 ? 'active-img' : 'inactive-img'"
      >
        <mat-icon fontIcon="folder"></mat-icon>
        Folders
      </p>
    </div>

    <div class="gallery-back">
      <img
        [@fadeInOut]="animState"
        [src]="pictures[activePic].src"
        alt="Showcase images for linkstorage"
      />
    </div>
  </section>

  <section class="home_transparency">
    <div class="home_transparency_title">
      <h1>Our Source Code</h1>
      <p>Full transparency, code in its purest form.</p>
    </div>

    <div class="home_transparency_content">
      <a href="https://github.com/JasonCqq/link-saver" target="_blank">
        <img
          src="../../../assets/transparency.png"
          alt="Image of linkstorage's github source code"
        />
      </a>
    </div>
  </section>

  <section #home_features class="home_features">
    <h1>Our Features</h1>

    <div class="home-features-grid">
      <div class="home-features-item">
        <span>
          <mat-icon fontIcon="description"></mat-icon>
        </span>

        <span>
          <h2>URL Bank</h2>
          <p>Quickly store multiple links in text format</p>
        </span>
      </div>

      <div class="home-features-item">
        <span>
          <mat-icon fontIcon="view_list"></mat-icon>
        </span>

        <span>
          <h2>Auto group (In Prog.)</h2>
          <p>Automatically group similar websites</p>
        </span>
      </div>

      <div class="home-features-item">
        <span>
          <mat-icon fontIcon="share"></mat-icon>
        </span>

        <span>
          <h2>Share links/folders</h2>
          <p>
            Share publicly or privately with a password.
            <a routerLink="/public/1" target="_blank"
              ><u>Check out our folder!</u></a
            >
          </p>
        </span>
      </div>

      <div class="home-features-item">
        <span>
          <mat-icon fontIcon="panorama"></mat-icon>
        </span>

        <span>
          <h2>Thumbnails</h2>
          <p>Easily preview stored links with website thumbnails.</p>
        </span>
      </div>

      <div class="home-features-item">
        <span>
          <mat-icon fontIcon="manage_search"></mat-icon>
        </span>

        <span>
          <h2>Search/Filter</h2>
          <p>Find links with search/sort functions, by visits name or date</p>
        </span>
      </div>

      <div class="home-features-item">
        <span>
          <mat-icon fontIcon="edit_note"></mat-icon>
        </span>

        <span>
          <h2>Mass Edit</h2>
          <p>Quickly edit/move/delete multiple links at once.</p>
        </span>
      </div>
    </div>
  </section>

  <section id="home_faq" class="home_faq">
    <div class="home-faq-title">
      <h1>Frequently Asked Questions</h1>

      <p>
        Have questions? Have a read through some of our FAQs <br />
        or contact us below or on github
      </p>
    </div>

    <div class="home-faq-container">
      <div
        class="faq-item"
        *ngFor="let faq of faqs"
        (click)="toggleFAQ(faq.id)"
      >
        <div class="faq-flex">
          <p>{{ faq.question }}</p>
          <span class="material-icons-round faq-icon">add</span>
        </div>
        <p class="faq-answer" *ngIf="activeID === faq.id">{{ faq.answer }}</p>
      </div>
    </div>
  </section>

  <section id="home_contact" class="home_contact">
    <div class="contact-title" (click)="toggleContact()">
      <h1>CONTACT US</h1>
      <span class="material-icons-round"> north_east </span>
    </div>

    <div class="contact-overlay" *ngIf="contactForm">
      <span
        class="material-icons-round"
        (click)="toggleContact()"
        style="margin: 10px"
      >
        close
      </span>
      <form
        class="contact-form"
        action="https://formsubmit.co/jason.cq.huang@gmail.com"
        method="POST"
      >
        <h1>Contact</h1>
        <div class="contact-flex">
          <mat-form-field appearance="outline" floatLabel="always">
            <mat-label for="name">Name</mat-label>
            <input matInput type="text" #name required name="name" />
          </mat-form-field>

          <mat-form-field appearance="outline" floatLabel="always">
            <mat-label for="email">Email</mat-label>
            <input matInput type="email" #email required name="email" />
          </mat-form-field>
        </div>

        <mat-form-field
          class="home-message"
          appearance="outline"
          floatLabel="always"
        >
          <mat-label for="message">Message</mat-label>
          <textarea
            matInput
            #message
            type="text"
            required
            name="message"
            rows="7"
          ></textarea>
        </mat-form-field>

        <button type="submit">Send Message</button>
      </form>
    </div>
  </section>

  <footer class="foot-note">
    <p routerLink="/versions">v2.1.0</p>

    <a href="https://github.com/JasonCqq/link-saver" target="_blank"
      >Source Code</a
    >

    <a
      href="https://www.termsfeed.com/live/a23806e5-a8bc-4542-a4fc-230353a493dc"
      target="_blank"
      >Privacy Policy</a
    >
  </footer>
</main>

// Frontend/src/Components/Home.tsx
import React, { useState } from "react";
import "../Styles/Home.scss";
import {
  AiOutlineCheck,
  AiFillPicture,
  AiFillFilter,
  AiOutlinePlus,
} from "react-icons/ai";
import { Link } from "react-router-dom";
import uniqid from "uniqid";

function Home() {
  const faqs = [
    {
      id: 1,
      question: "What is LinkStorage and how does it work?",
      answer:
        "Our website is a link saver tool that allows you to store and organize your favorite links all in one place. You can save URLs, filter and search through your collection, and even preview the content of the links directly on our platform.",
    },

    {
      id: 2,
      question: "Is my personal information or data shared with third parties?",
      answer:
        "No, your personal information or data will never be shared with third parties. We prioritize the security and privacy of your information.",
    },

    {
      id: 3,
      question: "Is there a browser extension for LinkStorage?",
      answer:
        "Not yet, but we're actively working on developing a browser extension to enhance your LinkStorage experience. Stay tuned for updates on this feature!",
    },

    {
      id: 4,
      question:
        "Do you offer a premium or paid version of LinkStorage with additional features?",
      answer:
        "No, every feature of LinkStorage is available for free. We believe in providing a comprehensive and valuable link-saving experience to all our users.",
    },

    {
      id: 5,
      question: "What features are available on LinkStorage?",
      answer:
        "LinkStorage offers a range of features to streamline your link-saving process, including filtering options like sorting and searching, thumbnail previews for easy identification, reminders to keep you organized, and the ability to create folders for efficient categorization.",
    },

    {
      id: 6,
      question: "What types of links can I save? Are there any restrictions?",
      answer:
        "There are no restrictions on the types of links you can save in LinkStorage. You can save links to websites, articles, videos, and more, making it a versatile tool for all your link-saving needs.",
    },

    {
      id: 7,
      question: "Can I share my folders/links to others?",
      answer:
        "Absolutely! You have the ability to generate shareable links for your folders, allowing you to easily share collections of links with others.",
    },

    {
      id: 8,
      question:
        "How can I suggest new features or improvements for LinkStorage?",
      answer:
        "We value your input! To suggest new features or improvements for LinkStorage, please visit our Contact Section below. We're always eager to hear your ideas and make our platform even better based on user feedback.",
    },
  ];

  const [activeID, setActiveID] = useState(0);

  const toggleFAQ = (id: number) => {
    setActiveID(activeID === id ? 0 : id);
  };

  return (
    <main className="home-page">
      <nav>
        <ul className="nav-bar">
          <a href="#" id="logo">
            LinkStorage
          </a>

          <div className="nav-mid">
            <a href="#home-features">About</a>
            <a href="#home-faq">FAQ</a>
            <a href="#home-contact">Contact</a>
          </div>

          <div className="nav-right">
            <Link to="login">Log in</Link>
            <Link to="register" id="getStarted">
              Get Started
            </Link>
          </div>
        </ul>
      </nav>

      <header className="landing-page">
        <div className="landing-heading">
          <section>Keep all your links in one place</section>
        </div>
        <p>125,258 links saved</p>
      </header>

      <section id="home-features">
        <h1>Why Us?</h1>
        <div className="home-features-flex">
          <div className="home-features-item">
            <AiFillFilter color={"#5b4dbe"} size={75} />
            <h2>Filtering</h2>
            <p>
              Quickly find your links. With a few clicks, you can locate your
              links, making it simple.
            </p>
          </div>
          <div className="home-features-item">
            <AiFillPicture color={"#5b4dbe"} size={75} />
            <h2>Visualization</h2>
            <p>
              Every saved link comes with a thumbnail, allowing you to identify
              your content at a glance.
            </p>
          </div>
          <div className="home-features-item">
            <AiOutlineCheck color={"#5b4dbe"} size={75} />
            <h2>Simplified</h2>
            <p>
              Hassle-free link saving with our user-friendly interface, making
              it easy to stay organized
            </p>
          </div>
        </div>
      </section>

      <section id="home-faq">
        <h1>FAQ</h1>

        <div className="home-faq-container">
          {faqs.map((faq) => {
            return (
              <div
                className="faq-item"
                key={uniqid()}
                onClick={() => toggleFAQ(faq.id)}
              >
                <div className="faq-flex">
                  <p>{faq.question}</p>
                  <AiOutlinePlus color={"#5b4dbe"} size={30} />
                </div>

                {activeID === faq.id && (
                  <p className="faq-answer">{faq.answer}</p>
                )}
              </div>
            );
          })}
        </div>
      </section>

      <footer id="home-contact">
        <h1>CONTACT</h1>
        <form className="contact-form">
          <div>
            <label htmlFor="name">NAME</label>
            <input type="text" id="name" name="name" required></input>
          </div>

          <div>
            <label htmlFor="email">EMAIL</label>
            <input type="email" id="email" name="email" required></input>
          </div>

          <div>
            <label htmlFor="subject">SUBJECT</label>
            <input type="text" id="subject" name="subject" required></input>
          </div>

          <label htmlFor="message">MESSAGE</label>
          <textarea id="message" name="message" required></textarea>

          <button type="submit">Send Message</button>
        </form>
      </footer>
    </main>
  );
}

export default Home;
