// Frontend/src/app/Components/login/login.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["../register/register.component.scss"],
})
export class LoginComponent {}

<main class="register-container">
  <a class="home-ref" routerLink="/home"> LinkStorage </a>

  <form class="register-form">
    <h1>Log in</h1>

    <div>
      <label>Username *</label>
      <input />
    </div>

    <div>
      <label>Password *</label>
      <input />
    </div>

    <button type="submit">Login</button>
  </form>

  <p>——— or ———</p>

  <button class="google-auth">Continue with Google</button>

  <a class="login-ref" routerLink="/register">
    Dont have an account? Register
  </a>
</main>

// Frontend/Components/Login.tsx
import React from "react";
import "../Styles/Register.scss";
import { Link } from "react-router-dom";

function Login() {
  return (
    <main className="register-container">
      <Link to="/" className="home-ref">
        LinkStorage
      </Link>

      <form className="register-form">
        <h1>Log in</h1>

        <div>
          <label>Username *</label>
          <input></input>
        </div>

        <div>
          <label>Password *</label>
          <input></input>
        </div>

        <button type="submit">Login</button>
      </form>

      <p>——— or ———</p>

      <button className="google-auth">Continue with Google</button>

      <Link className="login-ref" to="/register">
        Dont have an account? Register
      </Link>
    </main>
  );
}

export default Login;
