// Frontend/src/app/Components/register/register.component.ts
import { Component, OnInit } from "@angular/core";
import { FormControl, FormGroup, Validators } from "@angular/forms";
import { RegisterService } from "./register.service";

@Component({
  selector: "app-register",
  templateUrl: "./register.component.html",
  styleUrls: ["./register.component.scss"],
})
export class RegisterComponent implements OnInit {
  constructor(private registerService: RegisterService) {}

  applyForm = new FormGroup({
    username: new FormControl("", [Validators.required]),
    email: new FormControl("", [Validators.required, Validators.email]),
    password: new FormControl("", [
      Validators.required,
      Validators.minLength(8),
      Validators.maxLength(20),
    ]),
  });

  submitApplication(): void {
    this.registerService.submitApplication(
      this.applyForm.value.username ?? "",
      this.applyForm.value.email ?? "",
      this.applyForm.value.password ?? "",
    );
  }

  ngOnInit(): void {
    this.applyForm.valueChanges.subscribe();
  }

  get email() {
    return this.applyForm.get("email");
  }

  get username() {
    return this.applyForm.get("username");
  }

  get password() {
    return this.applyForm.get("password");
  }
}

<main class="register-container">
  <a class="home-ref" routerLink="/home"> LinkStorage </a>

  <form
    class="register-form"
    [formGroup]="applyForm"
    (submit)="submitApplication()"
  >
    <h1>Sign Up</h1>

    <div>
      <label for="username">Username *</label>

      <input id="username" formControlName="username" />
      <mat-error *ngIf="username?.invalid && username?.touched"
        >Username required</mat-error
      >
    </div>
    <div>
      <label for="email">Email address *</label>

      <input id="email" formControlName="email" />
      <mat-error *ngIf="email?.invalid && email?.touched"
        >Invalid Email</mat-error
      >
    </div>

    <div>
      <label for="password">Password *</label>

      <input
        id="password"
        type="password"
        formControlName="password"
        placeholder="8-20 characters"
      />
      <mat-error *ngIf="password?.invalid && password?.touched"
        >Invalid Password</mat-error
      >
    </div>

    <button type="submit" mat-raised-button [disabled]="applyForm.invalid">
      Register
    </button>

    <a class="login-ref" routerLink="/login">
      Already have an account? Log in
    </a>
  </form>
</main>

// Frontend/Components/Register.tsx
import React from "react";
import "../Styles/Register.scss";
import { Link } from "react-router-dom";

function Register() {
  return (
    <main className="register-container">
      <Link to="/" className="home-ref">
        LinkStorage
      </Link>

      <form className="register-form">
        <h1>Sign Up</h1>

        <div>
          <label>Username *</label>
          <input></input>
        </div>
        <div>
          <label>Email address *</label>
          <input></input>
        </div>

        <div>
          <label>Password *</label>
          <input></input>
        </div>

        <button type="submit">Register</button>
      </form>

      <p>——— or ———</p>

      <button className="google-auth">Continue with Google</button>

      <Link className="login-ref" to="/login">
        Already have an account? Log in
      </Link>
    </main>
  );
}

export default Register;
