// Frontend/src/Components/Home.tsx
import React, { useState } from "react";
import "../Styles/Home.scss";
import {
  AiOutlineCheck,
  AiFillPicture,
  AiFillFilter,
  AiOutlinePlus,
} from "react-icons/ai";
import { Link } from "react-router-dom";
import uniqid from "uniqid";

function Home() {
  const faqs = [
    {
      id: 1,
      question: "What is LinkStorage and how does it work?",
      answer:
        "Our website is a link saver tool that allows you to store and organize your favorite links all in one place. You can save URLs, filter and search through your collection, and even preview the content of the links directly on our platform.",
    },

    {
      id: 2,
      question: "Is my personal information or data shared with third parties?",
      answer:
        "No, your personal information or data will never be shared with third parties. We prioritize the security and privacy of your information.",
    },

    {
      id: 3,
      question: "Is there a browser extension for LinkStorage?",
      answer:
        "Not yet, but we're actively working on developing a browser extension to enhance your LinkStorage experience. Stay tuned for updates on this feature!",
    },

    {
      id: 4,
      question:
        "Do you offer a premium or paid version of LinkStorage with additional features?",
      answer:
        "No, every feature of LinkStorage is available for free. We believe in providing a comprehensive and valuable link-saving experience to all our users.",
    },

    {
      id: 5,
      question: "What features are available on LinkStorage?",
      answer:
        "LinkStorage offers a range of features to streamline your link-saving process, including filtering options like sorting and searching, thumbnail previews for easy identification, reminders to keep you organized, and the ability to create folders for efficient categorization.",
    },

    {
      id: 6,
      question: "What types of links can I save? Are there any restrictions?",
      answer:
        "There are no restrictions on the types of links you can save in LinkStorage. You can save links to websites, articles, videos, and more, making it a versatile tool for all your link-saving needs.",
    },

    {
      id: 7,
      question: "Can I share my folders/links to others?",
      answer:
        "Absolutely! You have the ability to generate shareable links for your folders, allowing you to easily share collections of links with others.",
    },

    {
      id: 8,
      question:
        "How can I suggest new features or improvements for LinkStorage?",
      answer:
        "We value your input! To suggest new features or improvements for LinkStorage, please visit our Contact Section below. We're always eager to hear your ideas and make our platform even better based on user feedback.",
    },
  ];

  const [activeID, setActiveID] = useState(0);

  const toggleFAQ = (id: number) => {
    setActiveID(activeID === id ? 0 : id);
  };

  return (
    <main className="home-page">
      <nav>
        <ul className="nav-bar">
          <li id="logo">LinkStorage</li>

          <div className="nav-mid">
            <a href="#home-features">About</a>
            <a href="#home-contact">Contact</a>
            <a href="#home-faq">FAQ</a>
          </div>

          <div className="nav-right">
            <a>Log in</a>
            <Link to="register" id="getStarted">
              Get Started
            </Link>
          </div>
        </ul>
      </nav>

      <header className="landing-page">
        <div className="landing-heading">
          <section>Keep all your links in one place</section>
        </div>
        <p>125,258 links saved</p>
      </header>

      <section id="home-features">
        <h1>Why Us?</h1>
        <div className="home-features-flex">
          <div className="home-features-item">
            <AiFillFilter color={"#5b4dbe"} size={75} />
            <h2>Filtering</h2>
            <p>
              Quickly find your links. With a few clicks, you can locate your
              links, making it simple.
            </p>
          </div>
          <div className="home-features-item">
            <AiFillPicture color={"#5b4dbe"} size={75} />
            <h2>Visualization</h2>
            <p>
              Every saved link comes with a thumbnail, allowing you to identify
              your content at a glance.
            </p>
          </div>
          <div className="home-features-item">
            <AiOutlineCheck color={"#5b4dbe"} size={75} />
            <h2>Simplified</h2>
            <p>
              Hassle-free link saving with our user-friendly interface, making
              it easy to stay organized
            </p>
          </div>
        </div>
      </section>

      <section id="home-faq">
        <h1>FAQ</h1>

        <div className="home-faq-container">
          {faqs.map((faq) => {
            return (
              <div className="faq-item" key={uniqid()}>
                <div className="faq-flex" onClick={() => toggleFAQ(faq.id)}>
                  <p>{faq.question}</p>
                  <AiOutlinePlus color={"#5b4dbe"} size={30} />
                </div>

                {activeID === faq.id && (
                  <p className="faq-answer">{faq.answer}</p>
                )}
              </div>
            );
          })}
        </div>
      </section>

      <footer id="home-contact">
        <h1>CONTACT</h1>
        <form className="contact-form">
          <div>
            <label htmlFor="name">NAME</label>
            <input type="text" id="name" name="name" required></input>
          </div>

          <div>
            <label htmlFor="email">EMAIL</label>
            <input type="email" id="email" name="email" required></input>
          </div>

          <div>
            <label htmlFor="subject">SUBJECT</label>
            <input type="text" id="subject" name="subject" required></input>
          </div>

          <label htmlFor="message">MESSAGE</label>
          <textarea id="message" name="message" required></textarea>

          <button type="submit">Send Message</button>
        </form>
      </footer>
    </main>
  );
}

export default Home;

// Frontend/src/app/Components/home copy/home.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import { UserService } from "../user/user.service";
import { HomeService } from "./home.service";
import { Subject, takeUntil } from "rxjs";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.scss"],
})
export class HomeComponent implements OnInit, OnDestroy {
  // Checks for user
  constructor(
    private userService: UserService,
    private homeService: HomeService,
  ) {}

  private destroy$ = new Subject<void>();

  user: any;
  data: any;

  videoShowcase: boolean = false;
  toggleShowcase() {
    this.videoShowcase = !this.videoShowcase;
  }

  ngOnInit() {
    this.userService.user$.pipe(takeUntil(this.destroy$)).subscribe((user) => {
      this.user = user?.user;
    });

    this.homeService
      .getStats()
      .pipe(takeUntil(this.destroy$))
      .subscribe((response) => {
        this.data = response;
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  // Toggle FAQ
  activeID: number = 0;
  toggleFAQ(id: number): void {
    this.activeID = this.activeID === id ? 0 : id;
  }

  faqs = [
    {
      id: 1,
      question: "What is LinkStorage and how does it work?",
      answer:
        "Our website is a link saver tool that allows you to store your links you want to revisit. Save any URLs with previews and other features!",
    },

    {
      id: 2,
      question: "Is my personal information or data shared?",
      answer:
        "No, your personal information or data will never be shared with third parties. We prioritize the security and privacy of your information.",
    },

    {
      id: 3,
      question: "Is there a browser extension for LinkStorage?",
      answer:
        "Not yet, but we plan on developing a browser extension that saves all the current tabs. Stay tuned for updates on this feature!",
    },

    {
      id: 4,
      question: "What features are available on LinkStorage?",
      answer:
        "LinkStorage offers a range of features including filtering such as searching, thumbnail screenshots, reminders, and folders for efficient organization.",
    },

    {
      id: 5,
      question: "Any restriction on types of links can I save?",
      answer:
        "There are no restrictions on the types of links you can save. You can save links to websites, articles, videos, and more.",
    },

    {
      id: 6,
      question: "Can I share my folders/links to others?",
      answer:
        "Yes! You can generate shareable links for your folders publicly or privately behind a password for others.",
    },

    {
      id: 7,
      question: "How can I suggest features/improvements?",
      answer:
        "We value your input! To suggest new features or improvements for LinkStorage, please visit our Contact Section below. We're always eager to hear your ideas and make our platform even better based on user feedback.",
    },
  ];
}
